#pragma config(Sensor, dgtl8,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Move(int left,int right) {
	motor[leftMotor] = left;
	motor[rightMotor] = right;
}

void GetDirection(char* dir) {
	if (dir == "backward") {
		Move(80, 80);
	}
	else if (dir == "forward") {
		if (SensorValue[Sonar] >= 20) {
			Move(-80, -80);
		} else {
			Move(20, 20);
			wait1Msec(1000);
			Move(0, 0);
		}
	}
	else if (dir == "turnleft") {
		Move(80, -80);
	}
	else if (dir == "turnright") {
		Move(-80, 80);
	}
	else {
		Move(0, 0);
	}
}

task main() {
	displayLCDCenteredString(0, "Hello World!");
	wait1Msec(1000);
	
	clearLCDLine(0);
	clearLCDLine(1);
	while (true) {
			while (vexRT[Btn6D] == 1) {
				GetDirection("forward");
			}
			while (vexRT[Btn5D] == 1) {
				GetDirection("backward");
			}
			while (vexRT[Ch4] >= 10) {
				GetDirection("turnleft");
			}
			while (vexRT[Ch4] <= -10) {
				GetDirection("turnright");
			}
			GetDirection("NONE");
			
			
			
			displayLCDPos(0, 0);
			displayNextLCDString("Sonar: ");
			displayLCDPos(0, 7);
			displayNextLCDNumber(SensorValue[Sonar], 4);
			displayLCDPos(0, 12);
			displayNextLCDString("cm");
	}
}
