#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void Move(int left,int right) {
	motor[leftMotor] = left;
	motor[rightMotor] = right;
}

void GetDirection(char* dir) {
	if (dir == "forward") {
		Move(80, 80);
	}
	else if (dir == "backward") {
		Move(-80, -80);
	}
	else if (dir == "turnleft") {
		Move(80, -80);
	}
	else if (dir == "turnright") {
		Move(-80, 80);
	}
	else {
		Move(0, 0);
	}
}

task main() {
	while (true) {
			while (vexRT[Btn6D] == 1) {
				GetDirection("forward");
			}
			while (vexRT[Btn5D] == 1) {
				GetDirection("backward");
			}
			while (vexRT[Ch4] >= 10) {
				GetDirection("turnleft");
			}
			while (vexRT[Ch4] <= -10) {
				GetDirection("turnright");
			}
			GetDirection("NONE");
	}
}
